VIA_ENABLE = yes
REPEAT_KEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes

# MACCEL
MACCEL_ENABLE = yes
MACCEL_VIA_ENABLE = yes

include $(MAIN_KEYMAP_PATH_3)/maccel/rules.mk

CONSOLE_ENABLE = yes
VIA_ENABLE = no
